// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: flutter pub run build_runner build --delete-conflicting-outputs
//
// This file will be auto-generated when you run build_runner.
// It is included here as a placeholder.

part of 'models.dart';

// ══════════════════════════════════════════════════
// TypeAdapters - auto-generated by hive_generator
// ══════════════════════════════════════════════════

class PasswordEntryAdapter extends TypeAdapter<PasswordEntry> {
  @override
  final int typeId = 0;

  @override
  PasswordEntry read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return PasswordEntry(
      id: fields[0] as String,
      site: fields[1] as String,
      username: fields[2] as String,
      encryptedPassword: fields[3] as String,
      notes: fields[4] as String,
      createdAt: fields[5] as DateTime,
      updatedAt: fields[6] as DateTime,
      iconEmoji: fields[7] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, PasswordEntry obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)..write(obj.id)
      ..writeByte(1)..write(obj.site)
      ..writeByte(2)..write(obj.username)
      ..writeByte(3)..write(obj.encryptedPassword)
      ..writeByte(4)..write(obj.notes)
      ..writeByte(5)..write(obj.createdAt)
      ..writeByte(6)..write(obj.updatedAt)
      ..writeByte(7)..write(obj.iconEmoji);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordEntryAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class DiaryEntryAdapter extends TypeAdapter<DiaryEntry> {
  @override
  final int typeId = 1;

  @override
  DiaryEntry read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return DiaryEntry(
      id: fields[0] as String,
      title: fields[1] as String,
      encryptedContent: fields[2] as String,
      mood: fields[3] as String,
      createdAt: fields[4] as DateTime,
      updatedAt: fields[5] as DateTime,
      tags: (fields[6] as List).cast<String>(),
    );
  }

  @override
  void write(BinaryWriter writer, DiaryEntry obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)..write(obj.id)
      ..writeByte(1)..write(obj.title)
      ..writeByte(2)..write(obj.encryptedContent)
      ..writeByte(3)..write(obj.mood)
      ..writeByte(4)..write(obj.createdAt)
      ..writeByte(5)..write(obj.updatedAt)
      ..writeByte(6)..write(obj.tags);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiaryEntryAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class FinanceRecordAdapter extends TypeAdapter<FinanceRecord> {
  @override
  final int typeId = 2;

  @override
  FinanceRecord read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return FinanceRecord(
      id: fields[0] as String,
      type: fields[1] as String,
      amount: fields[2] as double,
      category: fields[3] as String,
      description: fields[4] as String,
      date: fields[5] as DateTime,
      createdAt: fields[6] as DateTime,
      currency: fields[7] as String? ?? 'HKD',
      lineItemsJson: fields[8] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, FinanceRecord obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)..write(obj.id)
      ..writeByte(1)..write(obj.type)
      ..writeByte(2)..write(obj.amount)
      ..writeByte(3)..write(obj.category)
      ..writeByte(4)..write(obj.description)
      ..writeByte(5)..write(obj.date)
      ..writeByte(6)..write(obj.createdAt)
      ..writeByte(7)..write(obj.currency)
      ..writeByte(8)..write(obj.lineItemsJson);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FinanceRecordAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class VaultMetaAdapter extends TypeAdapter<VaultMeta> {
  @override
  final int typeId = 3;

  @override
  VaultMeta read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return VaultMeta(
      salt: fields[0] as String,
      verifyHash: fields[1] as String,
      createdAt: fields[2] as DateTime,
      lastUnlocked: fields[3] as DateTime,
      unlockCount: fields[4] as int,
      version: fields[5] as String,
    );
  }

  @override
  void write(BinaryWriter writer, VaultMeta obj) {
    writer
      ..writeByte(6)
      ..writeByte(0)..write(obj.salt)
      ..writeByte(1)..write(obj.verifyHash)
      ..writeByte(2)..write(obj.createdAt)
      ..writeByte(3)..write(obj.lastUnlocked)
      ..writeByte(4)..write(obj.unlockCount)
      ..writeByte(5)..write(obj.version);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultMetaAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
